import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {

  return (
    <div className="container-fluid d-flex align-items-end align-items-center justify-content-center">
      <Head>
        <meta name="description" content="Generated by DATAHOSTBD" />
      </Head>
      <h1 className="text-center card">Hello Hotels</h1>
    </div>
  )
}

export default Home
